src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 * @Vich\Uploadable
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length = 255)
     */
    private $Title;


    /**
     * @ORM\Column(type="text")
     */
    private $Content;


    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class, inversedBy="Questions")
     */
    private $Subject;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="Question")
     */
    private $Answers;
    // ... other fields

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="Question_image", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
     */
    private $Author;
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function __construct()
    {
        $this->Answers = new ArrayCollection();
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubject(): ?Subject
    {
        return $this->Subject;
    }

    public function setSubject(?Subject $Subject): self
    {
        $this->Subject = $Subject;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->Answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->Answers->contains($answer)) {
            $this->Answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->Answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\Question;
use App\Entity\Subject;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Content')
            ->add('Subject', EntityType::class, [
                'class' => Subject::class,
                'choice_label' => 'Title'
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => false,
                'download_uri' => false,
                'image_uri' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Entity\Question;
use App\Form\AnswerType;
use App\Form\QuestionType;
use App\Repository\QuestionRepository;
use Doctrine\ORM\Mapping\Id;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuestionController extends AbstractController
{
    /**
     * @Route("/", name="question")
     */
    public function index(QuestionRepository $questionRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $Questions = $paginator->paginate(
            $questionRepository->findAll(), /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );
        return $this->render('question/index.html.twig', [
            'Questions' => $Questions,
        ]);
    }

    /**
     * @Route("/question/new", name="question_new")
     */
    public function create(Request $request){
        if (!$this->getUser()) {
            throw $this->createAccessDeniedException();
        }
        $Question = new Question();
        $form = $this->createForm(QuestionType::class, $Question);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $Question->setCreatedAt(new \DateTime());
            $Question->setAuthor($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Question);
            $entityManager->flush();
            $this->addFlash(
                'success',
                'Your Question was Posted'
            );
            return $this->redirectToRoute('question');

        }
        return $this->render('question/new.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/question/{id}", name="question_show", requirement)
     */
    public  function  Show(Request $request, QuestionRepository $questionRepository)
    {
        $QuestionId = $request->attributes->get('id');
        $Question = $questionRepository->find($QuestionId);
        $Answer = new Answer();
        $AnswerForm = $this->createForm(AnswerType::class, $Answer);
        $AnswerForm->handleRequest($request);
        $this->addAnswer($AnswerForm, $Answer, $Question);
        return $this->render('question/Show.html.twig',[
            'Question'=>$Question,
            'AnswerForm' => $AnswerForm->createView()
        ]);

    }

    /**
     * @Route("/question/{id}/edit", name="question_edit")
     */
        public function edit(Question $question, Request $request)
    {
        if ($this->getUser() !== $question->getAuthor()) {
            throw $this->createAccessDeniedException();
        }
        $form = $this->createForm(QuestionType::class, $question);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
            $this->addFlash(
                'success',
                'Your Question was edited'
            );
            return $this->redirectToRoute('question_show', ['id' => $question->getId()]);
        }

        return $this->render('/question/edit.html.twig', [
            'Question' => $question,
            'editForm' => $form->createView()
        ]);
    }

    private function addAnswer($AnswerForm, $Answer, $Question)
    {
        if($AnswerForm->isSubmitted() && $AnswerForm->isValid()){
            $Answer->setCreatedAt(new \DateTimeImmutable());
            $Answer->setQuestion($Question);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Answer);
            $entityManager->flush();
            $this->addFlash(
                'success',
                'Your Answer was added'
            );
            return $this->redirectToRoute('question_show', ['id' => $Question->getId()]);
        }
    }


}

templates/question/Show.html.twig
{% extends 'base.html.twig' %}
{% form_theme AnswerForm 'bootstrap_4_layout.html.twig' %}
{% block title %}Question Details{% endblock %}
{% block body %}
    <style>
        .Question{
            border-radius: 10px;
            box-shadow: 0 10px 16px rgba(0, 0, 0, .25);
            margin-bottom: 40;
            margin-top: 40px;
            padding: 40px;
        }
        img{
            border-radius: 10px;
        }
    </style>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success mt-5 text-center">
            {{ message }}
        </div>
    {% endfor %}
    <section class="Question mr-3 mt-2" style="margin: 0px;padding: 0 20px;width: 40%">
        <article style="    width: 100%;
    display: block;
    justify-content: center;
    text-align: center;margin: 0 !important;padding: 15px" class="mb-3">
            <div style="display: flex;" class="mb-2">

                <img src="{{ asset('images/users/') }}{{ Question.author.imageName }}" width="60px"
                     height="60px" style="width:15%;margin-right: 30px" class="rounded-circle">

                <h6 class="mt-2"> {{ Question.author.FirstName }} {{ Question.author.LastName }}</h6>
            </div>

            <div class="metadat mb-1">
                <span class="badge badge-info">{{ Question.Title }}</span>
                {{ Question.CreatedAt | date('Y-m-d') }} at   {{ Question.CreatedAt | date('H:i') }}

                <span class="badge bg-success">{{ Question.Subject.Title }}</span>
                <span class="badge badge-primary ml-2">{{ Question.Answers | length  }} {{ (Question.Answers | length <= 1) ? 'Answer' : 'Answers' }}</span>
            </div>
            <div  style="width: 100%;">
                <img src="{{ asset('images/questions/') }}{{ Question.imageName }}" class="card-img-top" alt="Sunset Over the Sea" style="width: 200px;
    height: 250px;"/>
                <div class="card-body">
                    <p>{{ Question.Content }}</p>
                    {% if app.user == Question.Author %}
                        <a href="{{ path('question_edit', {'id': Question.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                    {% endif %}
                </div>
            </div>

        </article>
    </section>

    <h2 class="mt-5">{{ Question.Answers | length  }} {{ (Question.Answers | length <= 1) ? 'Answer' : 'Answers' }}</h2>
    <section class="mt-5">
        {% for Answer in Question.Answers %}
            <div class="card-header">
                {{ Answer.Author}} <small> {{ Answer.CreatedAt | date('Y-m-d')}} at {{ Answer.CreatedAt | date('H:i') }}</small>
            </div>
            <div class="card-body">
                <p>{{ Answer.Content }}</p>
            </div>
        {% endfor %}
    </section>
    <h2>Add Answer</h2>
    {{ form_start(AnswerForm) }}
    {{ form_widget(AnswerForm) }}
    <button class="btn btn-success mt-5">Add a Answer</button>
    {{ form_end(AnswerForm) }}
{% endblock %}

templates/question/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme editForm 'bootstrap_4_layout.html.twig' %}
{% block title %}Question Edit{% endblock %}

{% block body %}
    <h1>Edit a Question</h1>
    {{ form_start(editForm) }}
    {{ form_widget(editForm) }}
    <button class="btn btn-success mt-5">Edit</button>
    {{ form_end(editForm) }}
{% endblock %}

templates/question/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello QuestionController!{% endblock %}

{% block body %}
<style>
    .Question{
        border-radius: 10px;
        box-shadow: 0 10px 16px rgba(0, 0, 0, .25);
        margin-bottom: 40;
        margin-top: 40px;
        padding: 40px;
    }
    img{
        border-radius: 10px;
    }
</style>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success mt-5 text-center">
            {{ message }}
        </div>
    {% endfor %}

    <h1> ALL Questions</h1>
    <div style="width: 100%;display: flex;flex-direction: row">
        {% for Question in Questions %}
            <section class="Question mr-3" style="margin: 0px;padding: 0 20px;width: 40%">
                <article style="    width: 100%;
    display: block;
    justify-content: center;
    text-align: center;margin: 0 !important;padding: 15px" class="mb-3">
                    <div style="display: flex;" class="mb-2">

                            <img src="{{ asset('images/users/') }}{{ Question.author.imageName }}" width="60px"
                            height="60px" style="width:15%;margin-right: 30px" class="bg-info rounded-circle">

                        <h6 class="mt-2"> {{ Question.author.FirstName }} {{ Question.author.LastName }}</h6>
                    </div>

                    <div class="metadat mb-1">
                        <span class="badge badge-info">{{ Question.Title }}</span>
                        {{ Question.CreatedAt | date('Y-m-d') }} at   {{ Question.CreatedAt | date('H:i') }}

                        <span class="badge bg-success">{{ Question.Subject.Title }}</span>
                        <span class="badge badge-primary ml-2">{{ Question.Answers | length  }} {{ (Question.Answers | length <= 1) ? 'Answer' : 'Answers' }}</span>
                    </div>
                    <div  style="width: 100%;">
                        <img src="{{ asset('images/questions/') }}{{ Question.imageName }}" class="card-img-top" alt="Sunset Over the Sea" style="width: 200px;
    height: 250px;"/>
                        <div class="card-body">
                            <p class="card-text">{{ Question.Content | split(' ')[0] }}....</p>
                            <a href="{{ path('question_show', {'id' : Question.id}) }}">Read More</a>
                        </div>
                    </div>

                </article>
            </section>
        {% endfor %}
    </div>

    <div class="navigation mt-2">
        {{ knp_pagination_render(Questions) }}
    </div>
{% endblock %}

templates/question/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block title %}Create a Question{% endblock %}

{% block body %}
    <h1>Add a Question</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-5">Add</button>
    {{ form_end(form) }}
{% endblock %}